language: csharp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      dotnet: 3.1
      mono: none
      env: CONFIGURATION=Debug DOTNETCORE=1
    - os: linux
      dist: xenial
      sudo: required
      dotnet: 3.1
      mono: none
      env: CONFIGURATION=Release DOTNETCORE=1

script:
  - dotnet restore
  - dotnet build -c $CONFIGURATION ConvertVideos.sln
